/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSplitRouteImport } from './routes/tools/split'
import { Route as ToolsMergeRouteImport } from './routes/tools/merge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitRoute = ToolsSplitRouteImport.update({
  id: '/tools/split',
  path: '/tools/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergeRoute = ToolsMergeRouteImport.update({
  id: '/tools/merge',
  path: '/tools/merge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/merge' | '/tools/split'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/merge' | '/tools/split'
  id: '__root__' | '/' | '/tools/merge' | '/tools/split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsMergeRoute: typeof ToolsMergeRoute
  ToolsSplitRoute: typeof ToolsSplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split': {
      id: '/tools/split'
      path: '/tools/split'
      fullPath: '/tools/split'
      preLoaderRoute: typeof ToolsSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge': {
      id: '/tools/merge'
      path: '/tools/merge'
      fullPath: '/tools/merge'
      preLoaderRoute: typeof ToolsMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsMergeRoute: ToolsMergeRoute,
  ToolsSplitRoute: ToolsSplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
