/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWatermarkRouteImport } from './routes/tools/watermark'
import { Route as ToolsSplitRouteImport } from './routes/tools/split'
import { Route as ToolsRotateRouteImport } from './routes/tools/rotate'
import { Route as ToolsPageNumbersRouteImport } from './routes/tools/page-numbers'
import { Route as ToolsOrganizeRouteImport } from './routes/tools/organize'
import { Route as ToolsMergeRouteImport } from './routes/tools/merge'
import { Route as ToolsJpgToPdfRouteImport } from './routes/tools/jpg-to-pdf'
import { Route as ToolsCompressRouteImport } from './routes/tools/compress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWatermarkRoute = ToolsWatermarkRouteImport.update({
  id: '/tools/watermark',
  path: '/tools/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitRoute = ToolsSplitRouteImport.update({
  id: '/tools/split',
  path: '/tools/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRotateRoute = ToolsRotateRouteImport.update({
  id: '/tools/rotate',
  path: '/tools/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPageNumbersRoute = ToolsPageNumbersRouteImport.update({
  id: '/tools/page-numbers',
  path: '/tools/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOrganizeRoute = ToolsOrganizeRouteImport.update({
  id: '/tools/organize',
  path: '/tools/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergeRoute = ToolsMergeRouteImport.update({
  id: '/tools/merge',
  path: '/tools/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJpgToPdfRoute = ToolsJpgToPdfRouteImport.update({
  id: '/tools/jpg-to-pdf',
  path: '/tools/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressRoute = ToolsCompressRouteImport.update({
  id: '/tools/compress',
  path: '/tools/compress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/organize': typeof ToolsOrganizeRoute
  '/tools/page-numbers': typeof ToolsPageNumbersRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/organize': typeof ToolsOrganizeRoute
  '/tools/page-numbers': typeof ToolsPageNumbersRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/organize': typeof ToolsOrganizeRoute
  '/tools/page-numbers': typeof ToolsPageNumbersRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
  '/tools/watermark': typeof ToolsWatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/compress'
    | '/tools/jpg-to-pdf'
    | '/tools/merge'
    | '/tools/organize'
    | '/tools/page-numbers'
    | '/tools/rotate'
    | '/tools/split'
    | '/tools/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/compress'
    | '/tools/jpg-to-pdf'
    | '/tools/merge'
    | '/tools/organize'
    | '/tools/page-numbers'
    | '/tools/rotate'
    | '/tools/split'
    | '/tools/watermark'
  id:
    | '__root__'
    | '/'
    | '/tools/compress'
    | '/tools/jpg-to-pdf'
    | '/tools/merge'
    | '/tools/organize'
    | '/tools/page-numbers'
    | '/tools/rotate'
    | '/tools/split'
    | '/tools/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsCompressRoute: typeof ToolsCompressRoute
  ToolsJpgToPdfRoute: typeof ToolsJpgToPdfRoute
  ToolsMergeRoute: typeof ToolsMergeRoute
  ToolsOrganizeRoute: typeof ToolsOrganizeRoute
  ToolsPageNumbersRoute: typeof ToolsPageNumbersRoute
  ToolsRotateRoute: typeof ToolsRotateRoute
  ToolsSplitRoute: typeof ToolsSplitRoute
  ToolsWatermarkRoute: typeof ToolsWatermarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/watermark': {
      id: '/tools/watermark'
      path: '/tools/watermark'
      fullPath: '/tools/watermark'
      preLoaderRoute: typeof ToolsWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split': {
      id: '/tools/split'
      path: '/tools/split'
      fullPath: '/tools/split'
      preLoaderRoute: typeof ToolsSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rotate': {
      id: '/tools/rotate'
      path: '/tools/rotate'
      fullPath: '/tools/rotate'
      preLoaderRoute: typeof ToolsRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/page-numbers': {
      id: '/tools/page-numbers'
      path: '/tools/page-numbers'
      fullPath: '/tools/page-numbers'
      preLoaderRoute: typeof ToolsPageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/organize': {
      id: '/tools/organize'
      path: '/tools/organize'
      fullPath: '/tools/organize'
      preLoaderRoute: typeof ToolsOrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge': {
      id: '/tools/merge'
      path: '/tools/merge'
      fullPath: '/tools/merge'
      preLoaderRoute: typeof ToolsMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jpg-to-pdf': {
      id: '/tools/jpg-to-pdf'
      path: '/tools/jpg-to-pdf'
      fullPath: '/tools/jpg-to-pdf'
      preLoaderRoute: typeof ToolsJpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress': {
      id: '/tools/compress'
      path: '/tools/compress'
      fullPath: '/tools/compress'
      preLoaderRoute: typeof ToolsCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsCompressRoute: ToolsCompressRoute,
  ToolsJpgToPdfRoute: ToolsJpgToPdfRoute,
  ToolsMergeRoute: ToolsMergeRoute,
  ToolsOrganizeRoute: ToolsOrganizeRoute,
  ToolsPageNumbersRoute: ToolsPageNumbersRoute,
  ToolsRotateRoute: ToolsRotateRoute,
  ToolsSplitRoute: ToolsSplitRoute,
  ToolsWatermarkRoute: ToolsWatermarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
